services:
  postgres:
    image: postgres:16-alpine
    container_name: metrics-pg
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 3


  server:
    image: golang:1.26.1
    container_name: metrics-server
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      ADDRESS: "0.0.0.0:8080"
      DATABASE_DSN: ${DATABASE_DSN}
    command: go run ./cmd/server/main.go


  agent:  
    image: golang:1.26.1
    container_name: metrics-agent
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    environment:
      ADDRESS: "server:8080"
    command: go run ./cmd/agent/main.go

volumes:
  pg_data:






